baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "Noble Concrete and Construction"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo.jpg"
    mobile_height = "36px"
    desktop = "images/logo/logo.jpg"
    desktop_height = "36px"
    alt = "Noble Concrete and Construction"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#549F76"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_facebook_page = 'nobleconcreteandconstruction'
    meta_og_image = "https://scontent.fdet3-1.fna.fbcdn.net/v/t39.30808-6/338670091_745691310546654_3407945761893954293_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=-3-yqWgmYE4AX-r_Bbf&_nc_ht=scontent.fdet3-1.fna&oh=00_AfA6xmCdIJlgIwWl53gAuCWLPZV4beQ2wOkHYnG7D_kTLg&oe=64873184"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '©2023 Noble Concrete and Construction'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 1

  # [[menu.main]]
  #   name = "Team"
  #   url = "/team/"
  #   weight = 2

  # [[menu.main]]
  #   name = "About"
  #   url = "/about/"
  #   weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 2
